---
- hosts: all

  vars:
    PYTHON: "/usr/bin/python3"
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:

    # https://github.com/ansible/ansible/issues/25414#issuecomment-440549135
    - name: Wait for any possibly running unattended upgrade to finish
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
      become: yes

    - name: Install python3
      apt:
        pkg:
        - python3
        - python3-venv
        - python3-pip
      become: yes

    - name: Add source command to .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "source ~/env3/bin/activate"
        regex: "^source ~/env3/bin/activate$"
        state: present
        insertafter: EOF
        create: yes

    - name: Upgrade pip
      vars:
        ansible_python_interpreter: "{{ PYTHON }}"
      pip:
        name: pip
        state: latest
        virtualenv: ~/env3
        virtualenv_command: "{{ PYTHON }} -m venv"

    - name: Install imgurpython
      pip:
        name: imgurpython
        virtualenv: ~/env3
        virtualenv_command: "{{ PYTHON }} -m venv"

    - name: Install tex2pix
      pip:
        name: tex2pix
        virtualenv: ~/env3
        virtualenv_command: "{{ PYTHON }} -m venv"

    - name: Install pdf2image
      pip:
        name: pdf2image
        virtualenv: ~/env3
        virtualenv_command: "{{ PYTHON }} -m venv"

    - name: Install opencv-python
      pip:
        name: opencv-python
        virtualenv: ~/env3
        virtualenv_command: "{{ PYTHON }} -m venv"

    - name: install poppler-utils
      apt: 
        name: poppler-utils
        state: present
      become: yes

    - name: install latex
      apt: 
        name: texlive-latex-recommended
        state: present
      become: yes

    - name: install polish language
      apt: 
        name: texlive-lang-polish 
        state: present
      become: yes

    - name: set up nodejs sources
      shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo bash -
      become: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
      become: yes

    - name: install packages forms-app
      shell: npm i
      args:
        chdir: /vagrant/forms-app

    - name: install packages forms-app-ui
      shell: npm i
      args:
        chdir: /vagrant/forms-app-ui

    - name: Deploy forms-app
      copy:
        src: forms-app.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Deploy forms-app-ui
      copy:
        src: forms-app-ui.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    # Enable and run
    - name: Systemd daemon reload
      systemd:
        daemon_reload: yes
      become: yes

    - name: Enable and run forms-app service
      service:
        name: forms-app
        enabled: yes
        state: started
      become: yes

    - name: Enable and run forms-app-ui service
      service:
        name: forms-app-ui
        enabled: yes
        state: started
      become: yes
